batch_size: 16
n_epochs: 200
lr: 0.003
train_fpath: /workspace/skin/data/train_isic_titans_full.txt
val_fpath: /workspace/skin/data/validation_isic_titans_full.txt
train_preprocess: opening
val_preprocess: original
multimask: true