model: deeplab
batch_size: 16
n_epochs: 150
lr: 0.003
train_fpath: /workspace/skin/data/isic_2018_train_train.txt
val_fpath: /workspace/skin/data/isic_2018_train_validation.txt
train_preprocess: original
val_preprocess: original
multimask: false
patience: 20
